### ISSUE TITLE
Add the deep link to categories and labels in addition to the brand

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#180]
### What

Add a deep link to categories and labels in addition to the brand

### Why 
- More opportunity for serendipity validation if a label or category piques your interest.

### Part of 

- [ ] #236

#### Deep link for brands
![image](https://user-images.githubusercontent.com/1689815/108350792-f31a4780-71e4-11eb-865a-1cd864d16e8f.png)

#### No deep link for categories and labels (possibly because they are taxonomized?)
![image](https://user-images.githubusercontent.com/1689815/108350823-fa415580-71e4-11eb-8402-17ef04982304.png)
![image](https://user-images.githubusercontent.com/1689815/108350857-03cabd80-71e5-11eb-81a6-d7e660912e08.png)

**Comment by alexfauquette** [comment]
Difficult due to translations.
For example, `en:green-dot` get translated by the API to `EU-Öko-Verordnung` if we set `language=de`
but `tag_value` must be set to `en:green-dot` to filter product with this label

Two solutions : 
- Modify the API sich that `tag_value=eu-oko-verordnung` does the same as `tag_value=en:green-dot`
- Add a field `raw_tag` to the question sent by robotoff, such that the UI know which `tag_value` to ask
