### ISSUE TITLE
Hunger Games is making a 404 request to https://hunger.openfoodfacts.org/questions?type=label

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#275]
![image](https://user-images.githubusercontent.com/1689815/133093925-cdd9f93f-aa3e-465d-8e1b-28981c62fe8c.png)
Hunger Games is making a 404 request to https://hunger.openfoodfacts.org/questions?type=label

**Comment by teolemon** [comment]
And another to `Request URL: https://hunger.openfoodfacts.org/favicon.ico`

**Comment by alexfauquette** [comment]
The first one is normal, it is a hack to avoid modifying the URLs in the app.

From github page perspective, we only have two pages `index.html`, and `404.html`. So as soon as you ask for `https://hunger.openfoodfacts.org/blablabla` the file does not exist and it returns the 404.
To trick it, I replace the 404 content by the app

I see another way to cheat with it. We could create files `questions.html`, `logos.html`, ... such that it does not return a 404

**Comment by alexfauquette** [comment]
for the favicon, I don't know. To investigate

**Comment by alexfauquette** [comment]
I did the modification to avoid 404 errors on first loading. But for favicon, I don't know. It seems there is no favicon specification in this project. I assume your browser is looking by default for a file `favicon.ico` because mine does not send this request.

f you want to add a favicon, that's easy, but which one?
