### ISSUE TITLE
Integrate this Robotoff API to prepopulate the nutrition game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#359]
### What
- [ ] Integrate this Robotoff API to prepopulate the nutrition game
  - [ ] https://hunger.openfoodfacts.org/nutritions
  - [ ] https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://world.openfoodfacts.org/images/products/802/509/314/0251/4.json
  - [ ] https://world.openfoodfacts.org/images/products/802/509/314/0251/4.jpg

### Part of
- #234

**Comment by Jagrutiti** [comment]
Hi @teolemon integrating an API sounds like me. I would love to take this up.

Only if you could tell in more detail about what is expected. Thanks.

**Comment by alexfauquette** [comment]
Hi @Jagrutiti Did you looked at what are the given links

## To give you some context

- https://hunger.openfoodfacts.org/nutritions is an interface that allows users to see a picture of nutritional images, and fill the table
- robotoff is the server running AI to read and extract data from pictures by calling https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://world.openfoodfacts.org/images/products/802/509/314/0251/4.json You ask him what are the nutritional information available on the picture world.openfoodfacts.org/images/products/802/509/314/0251/4.jpg

![world.openfoodfacts.org/images/products/802/509/314/0251/4.jpg](https://world.openfoodfacts.org/images/products/802/509/314/0251/4.jpg)


## What to do in detail

In the code of the nutrition game you have to get the URL of the picture, send it to robotoff, and use that answer to fill the table input

**Comment by Jagrutiti** [comment]
Hi @alexfauquette thanks for explaining. 

I am not sure how to get the image detail to fetch nutrition value. 

![Screenshot from 2022-03-18 14-26-44](https://user-images.githubusercontent.com/28809492/158972205-8cfa4ab2-bf35-4279-95e2-5979ec66f22a.png)

To fetch the nutrition value of this component this is what I tried:

1. Passed the [link of the image](https://images.openfoodfacts.org/images/products/328/565/041/2312/nutrition_en.10.400.jpg). This URL was created: https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://images.openfoodfacts.org/images/products/328/565/041/2312/nutrition_en.10.400.json. The output is blank

2. Next I tried adding the `/` separated numbers. This url didn't work as well https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://world.openfoodfacts.org/images/products/328/565/041/2312.json

When you said:
> * You ask him what are the nutritional information available on the picture world.openfoodfacts.org/images/products/802/509/314/0251/4.jpg

**The problem is, I am not able to figure out where to get the image file path from.** 

This is the code to display images:
`<img
            :class="[imageRotationClass]"
            :src="productBuffer[0]['image_nutrition_url']"
            style="max-height: 300px;
          max-width: 300px;"
          />`

And if I have got the code right we get the image name from `productBuffer[0]['image_nutrition_url']`. But I am clueless further.

**Comment by alexfauquette** [comment]
That's because `nutrition_en.10.400` is not the original name of the image

Notice that https://images.openfoodfacts.org/images/products/328/565/041/2312/nutrition_en.10.400.json return a 404


For product with code 7897266800429

From the request that fetch task to do:
https://world.openfoodfacts.org/state/photos-validated/state/nutrition-facts-to-be-completed/10.json?fields=code,lang,image_nutrition_url,product_name

You have the following data
```
{
code: "7897266800429"
image_nutrition_url: "https://images.openfoodfacts.org/images/products/789/726/680/0429/nutrition_pt.9.400.jpg"
lang: "pt"
}
```

You can get images data with the following request
https://world.openfoodfacts.org/api/v0/product/7897266800429.json?fields=product_name,images
 which contains 

```
images: {
	...	
	nutrition_pt: {
		imgid: "3",
		...
	}
}
```

Then you can construct the URL to get the OCR: `https://images.openfoodfacts.org/images/products/789/726/680/0429/3.json`

Notice that the `7897266800429` becomes `789/726/680/0429`. I noticed that this occurs each time a code is 13 character long

Now you can pass the OCR to robotoff

https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://images.openfoodfacts.org/images/products/789/726/680/0429/3.json

**Comment by Jagrutiti** [comment]
> [https://world.openfoodfacts.org/state/photos-validated/state/nutrition-facts-to-be-completed/10.json?fields=code,lang,image_nutrition_url,product_name](https://world.openfoodfacts.org/state/photos-validated/state/nutrition-facts-to-be-completed/10.json?fields=code,lang,image_nutrition_url,product_name)

Could you tell me, how did you decide that you have to add `10` before `.json`.

Because as far as I have understood this value has some different meaning.

**Comment by alexfauquette** [comment]
What do you mean by?
> some different meaning

If I remember correctly, it's the page of the request, which is chosen randomly in hungergame. I just copy past the request sent by the app

**Comment by Jagrutiti** [comment]
I have written the code to call the API in `robotoff.js` file

 ```
getNutritionValueFromImage(code,imgid) {
    let getImageData = `${OFF_API_URL}${code}.json?fields=product_name,images`
   
    return axios.get(
      getImageData
    ).then(result => {
      var imageUrl= result[0]["image_nutrition_url"];
      var subStringUrl = imageUrl.substr(0, imageUrl.lastIndexOf("/"));

      return axios.get(
        `${ROBOTOFF_API_URL}/predict/nutrient?ocr_url=${subStringUrl}/${imgid}.json}`
      )
    })


```

And invoking in the `NutritionView.vue`

```
import { getNutritionValueFromImage as robotoffNutritionValue}from "../robotoff";

export default{
    ...
    methods:{
        getNutritionValue: async function(){
            const newProducts = await getProducts(20);      
            return robotoffNutritionValue(newProducts[0].code, newProducts[0].product.nutrition_pt.imgid);
            }
    }
    
}
```

Next will bind `getNutritionValue` to the table. 

**This is what I have understood from our discussion. Could you confirm if I am on the right track?**

Actually, I am new to Vue. I have to figure out the binding part. I am trying to invoke the function this way in vanilla JavaScript 
but the page stops turns blank.

```
<script>
  var val = NutritionView.getNutritionValue();
  console.log("vue val= ",val);
</script>

```
**Also, do you have any tips to view the output without binding the data? Thanks.**

**Comment by alexfauquette** [comment]
If you can write a PR, event a draft one, it will be easier to add comments in code and it will allow me to test your code when I've time

Don't try to call methods outside of the component. Just add a dummy component to test your code:
- to run a method add a button that calls it on click `<button @click="functionToTest()">Tets</button>`
- to see variable content, add a variable `<p>{{ theVariablImInterestedIn }}</p>`

If you have never done some react/vue before, I strongly recommend you to finish a tutorial before. the code is full of hacks, so the learning curves will be easier with a tutorial project

**Comment by Jagrutiti** [comment]
Hi @alexfauquette I have created this draft PR https://github.com/openfoodfacts/openfoodfacts-hungergames/pull/403

Also, I am at step-8 of [this Vue tutorial](https://vuejs.org/tutorial/). 

It is taking longer than expected so I thought you should make a PR for you to review. Thanks.
