### ISSUE TITLE
Add a link to products in a category/label/etc... in openfoodfacts while running game

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-hungergames#405]
### Story
- I'm playing robotoff in the category questions game https://hunger.openfoodfacts.org/questions?type=category
- The app asks me if a product belongs to the "chocolate cereal" category but I'm not sure which kind of products belongs to this category
- the app shows me a link under the category label to "show products in openfoodfacts" https://world.openfoodfacts.org/category/chocolate-cereals
- this helps my [baesyan brain](https://www.college-de-france.fr/site/stanislas-dehaene/course-2012-02-21-09h30.htm) to understand if I should answer yes / no or skip

This should be the same game on label and brands. (for weight it's not possible, of course)

**Comment by sumana2001** [comment]
Hi @alexgarel, what I understood from this issue is that you want the link in the below image to go to the Open Food Facts category link. Is that what you're expecting? 

<img width="384" alt="Screenshot 2022-03-21 at 7 05 32 PM" src="https://user-images.githubusercontent.com/63084088/159272220-8e397c42-804e-41ff-9df7-5c1cfe013b73.png">

I am interested to work on this issue, please assign it to me.

**Comment by alexgarel** [comment]
> Hi @alexgarel, what I understood from this issue is that you want the link in the below image to go to the Open Food Facts category link. Is that what you're expecting?

Not exactly, it should add a link below the image (the existing link leads to other snacks questions which is also useful).

You are welcome to work on it.
